feat: support EFRuP processor addition
frmscoe/typology-processor pull request #252
Opened 2024-08-07 15:08 UTC by Lenbkr

## What did we change?

Support for processing the EFRuP rule processor's results with its review outcome influence and interdiction blocking

## Why are we doing this?
EFRuP Functionality

## How was it tested?
- [x] Locally
- [ ] Development Environment
- [ ] Not needed, changes very basic
- [x] Husky successfully run
- [x] Unit tests passing and Documentation done

2024-08-08 12:26 UTC, cshezi submitted a review, later dismissed
LGTM

2024-08-08 13:50 UTC, Sandy-at-Tazama requested changes
1. typology-processor readme - this link appears outdated as it references CADP https://github.com/frmscoe/uml-diagrams/blob/main/TP.plantuml


3. typology-processor readme - typo in the sample typology configuration
![image](https://github.com/user-attachments/assets/25c82d5d-4b4e-468d-8852-fff34a050f97)

I am not sure if it matters, but should the `termId` come before the `wghts` object?
Should the `termId` not be "termId": "vEFRuPatnoneat100"

4.  typology-processor readme: The network map example references `channels`

![image](https://github.com/user-attachments/assets/898b35ac-8718-4c0b-bd0e-2c6f16e745d4)

 
5. __tests__/unit/logic.service.test.ts - inconsistent reference to EFRuP `TermId` in readme
termId: 'vEFRuPat100at100?

2024-08-08 14:52 UTC, Sandy-at-Tazama approved these changes

2024-08-12 08:11 UTC, Sandy-at-Tazama approved these changes

2024-08-12 08:21 UTC, rtkay123 approved these changes

2024-08-14 07:40 UTC, merged